### ISSUE TITLE
SSLError with fastly

### ISSUE THREAD

**Issue by shawnwall** [freshbooks/refreshbooks#28]
As of about a week ago, a site I have configured to use refreshbooks is now getting SSLError's. I tried upgrading `requests` and other networking libs but things still aren't working:

`hostname '<hidden>.freshbooks.com' doesn't match 'e.sni.fastly.net'`

**Comment by minichate** [comment]
Hey @shawnwall!

As part of our ongoing security program we've deprecated TLS 1.0/1.1. Along with that change, FreshBooks requires clients to support SNI (https://en.wikipedia.org/wiki/Server_Name_Indication). Most API clients, programming languages and operating systems have supported SNI for several years.

Specifically, Python newer than 2.7.9 is recommended/required now. There are hacks to support SNI/TLS 1.2 on older pythons but they come at the cost of a significant performance penalty.

**Comment by shawnwall** [comment]
Thank you for the info @minichate
